-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 01:40:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema leboncoin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leboncoin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leboncoin` DEFAULT CHARACTER SET utf8 ;
USE `leboncoin` ;

-- -----------------------------------------------------
-- Table `leboncoin`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leboncoin`.`USER` ;

CREATE TABLE IF NOT EXISTS `leboncoin`.`USER` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nom_user` VARCHAR(45) NULL,
  `prenom_user` VARCHAR(45) NULL,
  `mail_user` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leboncoin`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leboncoin`.`categorie` ;

CREATE TABLE IF NOT EXISTS `leboncoin`.`categorie` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(45) NULL,
  `marque` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leboncoin`.`Annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leboncoin`.`Annonce` ;

CREATE TABLE IF NOT EXISTS `leboncoin`.`Annonce` (
  `id_Annonce` INT NOT NULL AUTO_INCREMENT,
  `nom_annonce` VARCHAR(45) NULL,
  `detail` VARCHAR(45) NULL,
  `date_ajout` DATE NULL,
  `USER_id_user` INT NOT NULL,
  `categorie_id_categorie` INT NOT NULL,
  PRIMARY KEY (`id_Annonce`, `USER_id_user`, `categorie_id_categorie`),
  INDEX `fk_Annonce_USER1_idx` (`USER_id_user` ASC) VISIBLE,
  INDEX `fk_Annonce_categorie1_idx` (`categorie_id_categorie` ASC) VISIBLE,
  UNIQUE INDEX `id_Annonce_UNIQUE` (`id_Annonce` ASC) VISIBLE,
  CONSTRAINT `fk_Annonce_USER1`
    FOREIGN KEY (`USER_id_user`)
    REFERENCES `leboncoin`.`USER` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `leboncoin`.`categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leboncoin`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leboncoin`.`message` ;

CREATE TABLE IF NOT EXISTS `leboncoin`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `detail` VARCHAR(45) NULL,
  `Annonce_id_Annonce` INT NOT NULL,
  `USER_id_user` INT NOT NULL,
  PRIMARY KEY (`id_message`, `USER_id_user`, `Annonce_id_Annonce`),
  INDEX `fk_message_Annonce_idx` (`Annonce_id_Annonce` ASC) VISIBLE,
  INDEX `fk_message_USER1_idx` (`USER_id_user` ASC) VISIBLE,
  UNIQUE INDEX `Annonce_id_Annonce_UNIQUE` (`Annonce_id_Annonce` ASC) VISIBLE,
  CONSTRAINT `fk_message_Annonce`
    FOREIGN KEY (`Annonce_id_Annonce`)
    REFERENCES `leboncoin`.`Annonce` (`id_Annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_USER1`
    FOREIGN KEY (`USER_id_user`)
    REFERENCES `leboncoin`.`USER` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
